export const SHOW_SIDEBAR = 'SHOW_SIDEBAR';
export const CHAGE_CHECKBOX = 'CHAGE_CHECKBOX';
export const RECALCULATE_CURRENCY = 'RECALCULATE_CURRENCY';
export const DISPLAY_ERROR = 'DISPLAY_ERROR';
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_BACKDROP = 'CLOSE_BACKDROP';
export const SAVE_TICKET = 'SAVE_TICKET';
export const RESET_TICKET = 'RESET_TICKET';